version: '3.8'
services:
  php:
    build: .
    container_name: php-container
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8000 -t public

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony_password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
